"""Phantom (demo / offline) mode.

`PHANTOM_MODE=1` switches the helper to deterministic fixtures:

  - The RSS poller is NOT started; instead `preload()` populates the
    database with a known set of feed items so /api/feed returns
    something legible.
  - The channel prober is NOT started; preload also seeds every channel
    from seed.json (all ~21) to status=live with synthetic current_urls.
  - The fetcher's `default_resolver` is replaced with `phantom_resolver`
    so any code path that does try to make a real HTTP call refuses to
    resolve any hostname — phantom mode is a hard contract that no
    outbound traffic leaves the helper.

`tests/test_phantom.py` asserts this hard contract: a phantom app boot +
a /api/feed + a /api/channels request must produce zero outbound HTTP calls.
Run it with `uv run pytest -k phantom`. (A CI gate to run it on every push is
planned — see docs/adversarial-review-2026-06.md, DEPLOY-4.)
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta
from pathlib import Path

from . import db
from .channels import registry as channels_registry
from .feeds import parser as feed_parser
from .feeds import store as feed_store

log = logging.getLogger("mymts_helper.phantom")


class PhantomNetworkBlocked(Exception):
    """Raised if anything tries to do real DNS in phantom mode."""


async def phantom_resolver(host: str) -> list[str]:
    """The phantom resolver refuses every name. Phantom mode is a hard
    no-network contract — anything that gets this far is a bug we want
    to fail loudly, not paper over."""
    raise PhantomNetworkBlocked(f"network call attempted in phantom mode for: {host}")


PHANTOM_SOURCE_URL = "https://phantom.invalid/feed.xml"
PHANTOM_SOURCE_LABEL = "Phantom Sample Feed"


async def preload(db_path: Path) -> None:
    """Populate the DB with a small, stable set of fixtures.

    Idempotent: re-running preload on an already-preloaded DB inserts no
    new rows (dedup by guid + slug).
    """
    conn = db.connect(db_path)
    try:
        # Seed a phantom source + 3 items.
        sid = feed_store.upsert_source(
            conn, url=PHANTOM_SOURCE_URL, label=PHANTOM_SOURCE_LABEL
        )
        now = datetime(2026, 6, 1, 12, 0, 0, tzinfo=UTC)
        items = [
            feed_parser.ParsedItem(
                guid=f"phantom-{i}",
                title=f"Phantom item {i}",
                summary="Generated by helper phantom mode.",
                link=f"https://phantom.invalid/item/{i}",
                published_at=(now - timedelta(minutes=i)).strftime(
                    "%Y-%m-%dT%H:%M:%S.000Z"
                ),
            )
            for i in range(3)
        ]
        feed_store.insert_items(conn, sid, items)
        feed_store.record_fetch_success(conn, sid)

        # Mark seeded channels as live with their source_url as current_url.
        for c in channels_registry.list_channels(conn):
            channels_registry.update_status(
                conn,
                channel_id=c.id,
                status="live",
                current_url=c.source_url,
                error=None,
                success=True,
            )
        log.info("phantom_preload_complete")
    finally:
        conn.close()
